stages:
  - generate:html
  - pack
  - deploy

image: docker:stable

variables:
  REPOSITORY_NGINX: "${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_SLUG}:${CI_COMMIT_SHA}"

generate:html:
  stage: generate:html
  image: registry.gitlab.com/pages/hugo:latest
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    HUGO_ENV: production
  script:
    - hugo
  artifacts:
    paths:
      - public
  only:
    - master

pack:
  stage: pack
  variables:
    DOCKER_BUILD_ARG: '--squash'
  script:
    - mkdir ~/.docker
    - echo "${CI_JOB_TOKEN}" | docker login -u gitlab-ci-token --password-stdin "${CI_REGISTRY}"
    - docker pull "${NGINX_CONTAINER}"

    - docker build ${DOCKER_BUILD_ARG} --build-arg "NGINX_CONTAINER=${NGINX_CONTAINER}" -t "${REPOSITORY_NGINX}" -f docker/Dockerfile .
    - docker push "${REPOSITORY_NGINX}"
  services:
    - name: docker:stable-dind
      command: ["--experimental"]

deploy:jerry:
  stage: deploy
  #when: manual
  dependencies: []
  variables:
    GIT_STRATEGY: none
  script:
    - mkdir -p ~/.docker
    - echo "${CI_JOB_TOKEN}" | docker login -u gitlab-ci-token --password-stdin "${CI_REGISTRY}"

    - docker pull "${REPOSITORY_NGINX}"
    - docker tag "${REPOSITORY_NGINX}" "tremi:active"
    - docker rmi "${REPOSITORY_NGINX}"

    - dc-tremi up -d

    - docker logout "${CI_REGISTRY}"
  tags:
    - deploy
    - jerry
  only:
    - master
  except:
    - tags
